[workspace]
resolver = "2"
members = ["crates/jbl-quantum", "crates/quantumenginectl", "crates/quantumengine"]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/sidmax7/QuantumEngine"
rust-version = "1.75"

[workspace.dependencies]
jbl-quantum = { path = "crates/jbl-quantum", version = "0.1.0" }
